---
http_interactions:
- request:
    method: get
    uri: http://download.finance.yahoo.com/d/quotes.csv?f=sabn&s=GOOG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Sun, 22 Jan 2017 01:19:49 GMT
      P3p:
      - policyref="https://policies.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM
        DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND
        PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      Cache-Control:
      - private, no-cache, no-store
      Content-Length:
      - '37'
      Content-Type:
      - application/octet-stream
      Age:
      - '1'
      Via:
      - http/1.1 media-router-api2.prod.media.ir2.yahoo.com (ApacheTrafficServer [cMsSf
        ]), http/1.1 e13.ycpi.amb.yahoo.com (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '"GOOG",814.00,800.00,"Alphabet Inc."

'
    http_version: 
  recorded_at: Fri, 20 Jan 2017 00:00:00 GMT
- request:
    method: get
    uri: http://download.finance.yahoo.com/d/quotes.csv?f=snx&s=GOOG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Sun, 22 Jan 2017 01:19:49 GMT
      P3p:
      - policyref="https://policies.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM
        DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND
        PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      Cache-Control:
      - private, no-cache, no-store
      Content-Length:
      - '29'
      Content-Type:
      - application/octet-stream
      Age:
      - '3'
      Via:
      - http/1.1 media-router-api5.prod.media.ir2.yahoo.com (ApacheTrafficServer [cMsSf
        ]), http/1.1 e3.ycpi.amb.yahoo.com (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '"GOOG","Alphabet Inc.","NMS"

'
    http_version: 
  recorded_at: Fri, 20 Jan 2017 00:00:00 GMT
- request:
    method: get
    uri: http://ichart.finance.yahoo.com/table.csv?a=0&b=20&c=2016&d=0&e=19&f=2017&g=d&ignore=.csv&s=GOOG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Sun, 22 Jan 2017 01:19:49 GMT
      P3p:
      - policyref="http://info.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM DEV
        TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY
        ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      Content-Type:
      - text/csv
      Cache-Control:
      - private
      Vary:
      - Accept-Encoding,X-Ssl
      Age:
      - '0'
      Via:
      - http/1.1 yts247.global.media.ir2.yahoo.com (ApacheTrafficServer [cMsSf ]),
        http/1.1 e15.ycpi.amb.yahoo.com (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: |
        Date,Open,High,Low,Close,Volume,Adj Close
        2017-01-19,805.119995,809.47998,801.799988,802.174988,912000,802.174988
        2017-01-18,805.809998,806.205017,800.98999,806.070007,1294400,806.070007
        2017-01-17,807.080017,807.140015,800.369995,804.609985,1362100,804.609985
    http_version:
  recorded_at: Fri, 20 Jan 2017 00:00:00 GMT
recorded_with: VCR 3.0.3
