---
http_interactions:
- request:
    method: get
    uri: http://download.finance.yahoo.com/d/quotes.csv?f=sabn&s=GOOG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 19 Jan 2017 23:32:18 GMT
      P3p:
      - policyref="https://policies.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM
        DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND
        PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      Cache-Control:
      - private, no-cache, no-store
      Content-Length:
      - '39'
      Content-Type:
      - application/octet-stream
      Age:
      - '1'
      Via:
      - http/1.1 media-router-api2.prod.media.ir2.yahoo.com (ApacheTrafficServer [cMsSf
        ]), http/1.1 e28.ycpi.lob.yahoo.com (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '"GOOG",802.650,800.030,"Alphabet Inc."

'
    http_version: 
  recorded_at: Thu, 19 Jan 2017 23:32:18 GMT
- request:
    method: get
    uri: http://download.finance.yahoo.com/d/quotes.csv?f=snx&s=GOOG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 19 Jan 2017 23:32:18 GMT
      P3p:
      - policyref="https://policies.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM
        DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND
        PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      Cache-Control:
      - private, no-cache, no-store
      Content-Length:
      - '29'
      Content-Type:
      - application/octet-stream
      Age:
      - '0'
      Via:
      - http/1.1 media-router-api13.prod.media.ir2.yahoo.com (ApacheTrafficServer
        [cMsSf ]), http/1.1 e3.ycpi.lob.yahoo.com (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '"GOOG","Alphabet Inc.","NMS"

'
    http_version: 
  recorded_at: Thu, 19 Jan 2017 23:32:18 GMT
- request:
    method: get
    uri: http://ichart.finance.yahoo.com/table.csv?a=19&b=01&c=2016&s=GOOG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 19 Jan 2017 23:32:18 GMT
      P3p:
      - policyref="http://info.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM DEV
        TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY
        ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      Content-Type:
      - text/csv
      Cache-Control:
      - private
      Vary:
      - Accept-Encoding,X-Ssl
      Age:
      - '0'
      Via:
      - http/1.1 yts298.global.media.ir2.yahoo.com (ApacheTrafficServer [cMsSf ]),
        http/1.1 e16.ycpi.lob.yahoo.com (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: |
        Date,Open,High,Low,Close,Volume,Adj Close
        2017-01-18,805.809998,806.205017,800.98999,806.070007,1293300,806.070007
        2017-01-17,807.080017,807.140015,800.369995,804.609985,1355800,804.609985
        2017-01-13,807.47998,811.223999,806.690002,807.880005,1090100,807.880005
        2017-01-12,807.140015,807.390015,799.169983,806.359985,1351000,806.359985
        2017-01-11,805.00,808.150024,801.369995,807.909973,1057900,807.909973
        2017-01-10,807.859985,809.130005,803.51001,804.789978,1174300,804.789978
        2017-01-09,806.400024,809.966003,802.830017,806.650024,1272400,806.650024
        2017-01-06,795.26001,807.900024,792.203979,806.150024,1640200,806.150024
        2017-01-05,786.080017,794.47998,785.02002,794.02002,1335200,794.02002
        2017-01-04,788.359985,791.340027,783.159973,786.900024,1073000,786.900024
        2017-01-03,778.809998,789.630005,775.799988,786.140015,1657300,786.140015
    http_version:
  recorded_at: Thu, 19 Jan 2017 23:32:19 GMT
recorded_with: VCR 3.0.3
